import { SiteChrome, Eyebrow } from "./components/site-chrome";
import Link from "next/link";
import { courses, mediaTracks, references, works } from "./lib/content";

export default function Home() {
  return <SiteChrome>
    <section className="hero section-frame" id="top" aria-labelledby="hero-title">
      <div className="hero-copy"><Eyebrow number="01">PERSONAL PRACTICE · APP NODE</Eyebrow><h1 id="hero-title">不按默认轨道生活，<br /><em>把想法做成作品。</em></h1><p className="hero-lede">这里是张晓檬的一人公司、课程和自媒体 IP 实验室：用 AI、产品和持续行动，把真实经验整理成可以跟着走的内容。</p><div className="hero-meta"><span>人生实践记录者</span><i aria-hidden="true" /><span>9 款作品</span><i aria-hidden="true" /><span>课程筹备中</span></div><div className="hero-actions"><Link className="button button-primary" href="/courses">看课程方向 <span aria-hidden="true">↓</span></Link><a className="button button-quiet" href="/media">进入自媒体 IP <span aria-hidden="true">→</span></a></div></div>
      <div className="hero-art" aria-label="九款作品与持续实践的视觉标记"><div className="hero-art-paper" /><div className="hero-orbit hero-orbit-one" /><div className="hero-orbit hero-orbit-two" /><div className="hero-number"><span>9</span><small>WORKS<br />IN PROGRESS</small></div><span className="art-label art-label-top">MAKE<br /><b>IT REAL</b></span><span className="art-label art-label-bottom">KEEP<br /><b>GOING</b></span></div>
    </section>
    <section className="signal-strip section-frame" aria-label="实践状态"><div><span className="strip-label">当前入口</span><strong>app.yangmingjiuha.xyz</strong></div><div><span className="strip-label">正在记录</span><strong>人生 · 产品 · 注意力</strong></div><div><span className="strip-label">状态</span><strong className="live"><span className="status-dot" /> 持续中</strong></div></section>
      <section className="home-courses section-frame" id="courses"><div className="section-heading"><Eyebrow number="02">LEARN FROM THE WORK</Eyebrow><h2>把实践整理成课，<br /><em>但不假装已经完成。</em></h2></div><div className="home-course-grid">{courses.slice(0, 3).map((course) => <Link className={`course-card ${course.accent}`} href={`/courses/${course.slug}`} key={course.slug}><div className="course-top"><span>{course.number}</span><span className="course-status">{course.stage}</span></div><div className="course-copy"><h3>{course.title}</h3><span>{course.shortTitle}</span><p>{course.promise}</p></div><span className="course-foot">查看课程档案 →</span></Link>)}</div><Link className="text-link" href="/courses">查看全部课程方向 ↗</Link></section>
    <section className="home-media section-frame" id="media"><div><Eyebrow number="03">PERSONAL IP · CONTENT LAB</Eyebrow><h2>自媒体不是广告位，<br /><em>是长期记录。</em></h2><p>从真实创业、工具实践和作品复盘出发，先提供价值，再自然承接课程与产品。</p><a className="button button-quiet" href="/media">看内容架构 →</a></div><div className="media-grid">{mediaTracks.map((track) => <a className="media-card" href={`/media#${track.slug}`} key={track.slug}><span className="media-index">{track.number}</span><div><h3>{track.title}</h3><p>{track.text}</p></div><span className="media-arrow">↗</span></a>)}</div></section>
    <section className="home-story section-frame"><div className="story-stamp">LIFE<br /><b>AS A<br />PROJECT</b></div><div><Eyebrow number="04">A LIFE IN PRACTICE</Eyebrow><h2>工具是手段，<br /><em>主动生活才是方向。</em></h2><p>公司、代码、AI、书和电影，最后都会回到同一个问题：我想怎样使用自己的时间，又愿意为此承担什么。</p><a className="text-link" href="/story">读人生档案 ↗</a></div></section>
    <section className="works section-frame" id="works"><div className="works-heading"><div><Eyebrow number="05">WORKS ARCHIVE</Eyebrow><h2>9 款作品，<br /><em>是走过的路。</em></h2></div><p className="works-lede">这些产品来自清理、专注、记录、定价和创作等问题，共同构成一份仍在展开的个人实践档案。</p></div><div className="works-grid">{works.map((work) => <a className={`work-card ${work.accent}`} href={work.href} target="_blank" rel="noopener noreferrer" key={work.name}><div className="work-top"><span>{work.index}</span><span className="work-arrow">↗</span></div><div className="work-copy"><span className="work-type">{work.type}</span><h3>{work.name}</h3><p>{work.description}</p></div><span className="work-link">查看作品</span></a>)}</div></section>
    <section className="home-resources section-frame"><div><Eyebrow number="06">REFERENCE SHELF</Eyebrow><h2>方法可以借鉴，<br /><em>人生不能代做。</em></h2></div><div className="resource-grid">{references.map((reference) => <a className="resource-card" href={reference.href} target="_blank" rel="noreferrer" key={reference.title}><strong>{reference.title}</strong><span>{reference.note}</span><b>↗</b></a>)}</div></section>
  </SiteChrome>;
}
