/* eslint-disable @next/next/no-html-link-for-pages */
import { SiteChrome, Eyebrow } from "./components/site-chrome";
import { courses, mediaTracks, works } from "./lib/content";

export default function Home() {
  return <SiteChrome>
    <section className="hero section-frame" id="top" aria-labelledby="hero-title"><div className="hero-copy"><Eyebrow number="01">PERSONAL PRACTICE · APP NODE</Eyebrow><h1 id="hero-title">不按默认轨道生活，<br /><em>把想法做成作品。</em></h1><p className="hero-lede">这里是张晓檬的一人公司、课程和自媒体 IP 实验室：用 AI、产品和持续行动，把真实经验整理成可以跟着走的内容。</p><div className="hero-meta"><span>人生实践记录者</span><i aria-hidden="true" /><span>9 款作品</span><i aria-hidden="true" /><span>课程筹备中</span></div><div className="hero-actions"><a className="button button-workbench" href="/workbench">进入 AI 工作台 <span aria-hidden="true">↗</span></a><a className="button button-primary" href="/courses">看课程方向 <span aria-hidden="true">↓</span></a><a className="button button-quiet" href="/media">进入自媒体 IP <span aria-hidden="true">→</span></a></div></div><a className="hero-art" href="/workbench" aria-label="进入阳明 AI 工作台"><div className="hero-art-paper" /><div className="hero-orbit hero-orbit-one" /><div className="hero-orbit hero-orbit-two" /><div className="hero-number"><span>AI</span><small>WORKBENCH<br />LOCAL FIRST</small></div><span className="art-label art-label-top">THINK<br /><b>TOGETHER</b></span><span className="art-label art-label-bottom">MAKE<br /><b>IT REAL</b></span></a></section>
    <section className="signal-strip section-frame" aria-label="实践状态"><div><span className="strip-label">当前入口</span><strong>app.yangmingjiuha.xyz</strong></div><div><span className="strip-label">正在记录</span><strong>人生 · 产品 · 注意力</strong></div><div><span className="strip-label">状态</span><strong className="live"><span className="status-dot" /> 持续中</strong></div></section>
    <section className="home-courses section-frame" id="courses"><a className="section-heading section-heading-link" href="/courses"><Eyebrow number="02">LEARN FROM THE WORK</Eyebrow><h2>把实践整理成课，<br /><em>但不假装已经完成。</em></h2><span className="text-link">进入课程总览 ↗</span></a><div className="home-course-grid">{courses.slice(0, 3).map((course) => <a className={`course-card ${course.accent}`} href={`/courses/${course.slug}`} key={course.slug}><div className="course-top"><span>{course.number}</span><span className="course-status">{course.stage}</span></div><div className="course-copy"><h3>{course.title}</h3><span>{course.shortTitle}</span><p>{course.promise}</p></div><span className="course-foot">查看课程档案 →</span></a>)}</div></section>
    <section className="home-media section-frame" id="media"><a className="section-heading section-heading-link" href="/media"><Eyebrow number="03">PERSONAL IP · CONTENT LAB</Eyebrow><h2>自媒体不是广告位，<br /><em>是长期记录。</em></h2><p>从真实创业、工具实践和作品复盘出发，先提供价值，再自然承接课程与产品。</p><span className="button button-quiet">进入自媒体 IP 页面 →</span></a><div className="media-grid">{mediaTracks.map((track) => <a className="media-card" href={`/media#${track.slug}`} key={track.slug}><span className="media-index">{track.number}</span><div><h3>{track.title}</h3><p>{track.text}</p></div><span className="media-arrow">↗</span></a>)}</div></section>
    <section className="home-story section-frame"><a className="story-stamp" href="/story">LIFE<br /><b>AS A<br />PROJECT</b></a><a className="section-heading section-heading-link" href="/story"><Eyebrow number="04">A LIFE IN PRACTICE</Eyebrow><h2>工具是手段，<br /><em>主动生活才是方向。</em></h2><p>公司、代码、AI、书和电影，最后都会回到同一个问题：我想怎样使用自己的时间，又愿意为此承担什么。</p><span className="text-link">进入人生档案页面 ↗</span></a></section>
    <section className="works section-frame" id="works"><div className="works-heading"><div><a className="section-heading section-heading-link" href="/works"><Eyebrow number="05">WORKS ARCHIVE</Eyebrow><h2>9 款作品，<br /><em>是走过的路。</em></h2><span className="text-link">进入作品档案页面 ↗</span></a></div><p className="works-lede">这些产品来自清理、专注、记录、定价和创作等问题，共同构成一份仍在展开的个人实践档案。</p></div><div className="works-grid">{works.map((work) => <a className={`work-card ${work.accent}`} href={work.href} target="_blank" rel="noopener noreferrer" key={work.name}><div className="work-top"><span>{work.index}</span><span className="work-arrow">↗</span></div><div className="work-copy"><span className="work-type">{work.type}</span><h3>{work.name}</h3><p>{work.description}</p></div><span className="work-link">查看作品 ↗</span></a>)}</div></section>
    <section className="plan-teaser section-frame"><a className="section-heading section-heading-link" href="/plan"><Eyebrow number="06">IMPLEMENTATION PLAN</Eyebrow><h2>从记录到闭环，<br /><em>每一步都有下一步。</em></h2></a><div><p>把个人经历、口播、自媒体、课程、9 款作品和公司网站排成一条可执行路径。</p><a className="button button-primary" href="/plan">查看实施计划 →</a></div></section>
  </SiteChrome>;
}
